
#ansible-playbook -i votre_machine, create_users_groups.yaml --extra-vars "action=add utilisateurs_groupes_file=/chemin/vers/votre/fichier/utilisateurs_groupes.yaml"

---
- name: Gérer les utilisateurs et groupes
  hosts: all
  become: yes

  tasks:
    - name: Vérifier si l'action est valide
      fail:
        msg: "L'action doit être 'add[user-group]' ou 'del[user-group]'."
      when: action != 'adduser' and action != 'addgroup' and action != 'deluser' and action != 'delgroup'

    - name: Lire le fichier d'utilisateurs et groupes
      include_vars:
        file: "{{ utilisateurs_groupes_file }}"
        name: utilisateurs_groupes

    - name: Vérifier les utilisateurs existants
      shell: "getent passwd {{ item.nom }}"
      loop: "{{ utilisateurs_groupes.utilisateurs }}"
      register: existing_users
      ignore_errors: true
      when: action == 'adduser' or action == 'deluser'

    - name: Vérifier les groupes existants
      shell: "getent group {{ item.nom }}"
      loop: "{{ utilisateurs_groupes.groupes }}"
      register: existing_groups
      ignore_errors: true
      when: action == 'addgroup' or action == 'delgroup'

    - block:
        - name: Ajouter les utilisateurs
          include_tasks: add_users.yaml
          vars:
            utilisateurs: "{{ utilisateurs_groupes.utilisateurs }}"
          when: action == 'adduser'

        - name: Supprimer les utilisateurs
          include_tasks: delete_users.yaml
          vars:
            utilisateurs: "{{ utilisateurs_groupes.utilisateurs }}"
          when: action == 'deluser'

        - name: Ajouter les groupes
          include_tasks: add_groups.yaml
          vars:
            groupes: "{{ utilisateurs_groupes.groupes }}"
          when: action == 'addgroup'

        - name: Supprimer les groupes
          include_tasks: delete_groups.yaml
          vars:
            groupes: "{{ utilisateurs_groupes.groupes }}"
          when: action == 'delgroup'
