- name: Copier le script, accorder les droits d'execution
  hosts: all
  become: true
  remote_user: root
  tasks:
    - name: Copier le script.sh sur toutes les machines
      copy:
        src: /root/scripts/ansible/deployment_machines/load-key.sh
        dest: /root/load-key.sh
        mode: 0755
    - name: Copier la cle ssham
      copy:
        src: /root/scripts/ansible/deployment_machines/ssham-key
        dest: /root/ssham-key

    - name: Executer le script
      shell: /root/load-key.sh

    - name:
      file: Supprimer le load-key.sh
        path: /root/load-key.sh
        state: absent
    - name: Supprimer le ssham-key
      file:
        path: /root/ssham-key
        state: absent
