- name: Add users
  user:
    name: "{{ item.nom }}"
    state: present
  with_items: "{{ utilisateurs }}"

- name: Add users to groups
  user:
    name: "{{ item.nom }}"
    groups: "{{ item.groupes }}"
    append: yes
  loop: "{{ utilisateurs_groupes.utilisateurs }}"
  when: action == 'adduser'

- name: Copy ssham-key file on the server 
  copy:
    src: ../files/ssham-key"
    dest: "/root/ssham-key"
  when: action == 'adduser'

- name: Setup the bashrc file
  copy:
    src: "../files/.bashrc"
    dest: "/home/{{ item.nom }}/"
  with_items: "{{ utilisateurs }}"
  when: action == 'adduser'

- name: Modify the user shell to bash
  command: usermod -s /bin/bash "{{ item.nom }}"
  with_items: "{{ utilisateurs }}"
  when: action == 'adduser'

- name: Configure ssh keys for users
  become: yes
  become_user: root
  block:
    - name: Create .ssh directory for users
      file:
        path: "/home/{{ item.nom }}/.ssh"
        state: directory
      loop: "{{ utilisateurs }}"
      when: action == 'adduser'

    - name: Define permissions for .ssh directory for all users
      file:
        path: "/home/{{ item.nom }}/.ssh"
        owner: "{{ item.nom }}"
        group: "{{ item.nom }}"
        mode: '0700'
      loop: "{{ utilisateurs }}"
      when: action == 'adduser'

    - name: Append ssham-key to authorized_keys for all users
      shell: echo $(cat /root/ssham-key)   >>  /home/{{ item.nom }}/.ssh/authorized_keys
      loop: "{{ utilisateurs }}"
      when: action == 'adduser'

    - name: Define permissions of authorized_keys pour for all users
      file:
        path: "/home/{{ item.nom }}/.ssh/authorized_keys"
        owner: "{{ item.nom }}"
        group: "{{ item.nom }}"
        mode: '0600'
      loop: "{{ utilisateurs }}"
      when: action == 'adduser'

    - name: Delete the temporary  ssham-key file
      file:
        path: "/root/ssham-key"
        state: absent
  when: action == 'adduser'

